site_name: Welcome to Bioverse
site_description: A collection of my projects and experiences

nav:
  - Home: index.md
  - Projects:
      - Project 1: Projects/Project_1.md
      - Project 2: Projects/Project_2.md
      - Project 3: Projects/Project_3.md
      - Project 4: Projects/Project_4.md
      - Project 5: Projects/Project_5.md
      - Project 6: Projects/Project_6.md
      - Project 7: Projects/Project_7.md
  - Blogs:
      - USA_Free_education: https://bio.libretexts.org/Bookshelves/Evolutionary_Developmental_Biology/Evolutionary_Developmental_Biology_(Rivera)
      - EvoDir: https://evol.mcmaster.ca/evoldir.html
  - Contact: contact.md
  - Resume: Resume.md
  - Skills: Skills.md
